import { mkdir, open, readdir, rm, stat, statfs } from 'node:fs/promises';
import path from 'node:path';
import type { Logger } from './logger.js';
import { buildWavHeader, bytesPerSecond, parseWavHeader, WAV_HEADER_BYTES, type PcmFormat } from './wav.js';

/**
 * Recording filenames are generated by the server, so anything else is refused.
 * No path separators, no leading dot, no "..", must end in .wav.
 */
const SAFE_FILENAME = /^[A-Za-z0-9][A-Za-z0-9_-]{0,191}\.(?:wav|mp3)$/;
const NAME_PARTS = /^(.+)_(\d{4})-(\d{2})-(\d{2})_(\d{2})-(\d{2})-(\d{2})(?:_\d+)?\.(?:wav|mp3)$/;
const PARTIAL_FILE = /^[A-Za-z0-9][A-Za-z0-9_-]{0,191}\.mp3\.part$/;

export function contentTypeFor(filename: string): string {
  return filename.endsWith('.mp3') ? 'audio/mpeg' : 'audio/wav';
}

// MPEG-2 (16/22.05/24 kHz) and MPEG-1 Layer III bitrate tables, in kbps.
const MP3_BITRATES_V1 = [0, 32, 40, 48, 56, 64, 80, 96, 112, 128, 160, 192, 224, 256, 320];
const MP3_BITRATES_V2 = [0, 8, 16, 24, 32, 40, 48, 56, 64, 80, 96, 112, 128, 144, 160];

/** Bitrate (kbps) and start offset of the first Layer III frame, skipping an ID3v2 tag. */
export function parseMp3Start(buf: Buffer): { bitrateKbps: number; offset: number } | null {
  let off = 0;
  if (buf.length >= 10 && buf.toString('latin1', 0, 3) === 'ID3') {
    off = 10 + ((buf[6]! & 0x7f) << 21 | (buf[7]! & 0x7f) << 14 | (buf[8]! & 0x7f) << 7 | (buf[9]! & 0x7f));
  }
  for (let i = off; i + 4 <= buf.length; i++) {
    if (buf[i] !== 0xff || (buf[i + 1]! & 0xe0) !== 0xe0) continue;
    const version = (buf[i + 1]! >> 3) & 3; // 3 = MPEG-1, 2 = MPEG-2, 0 = MPEG-2.5
    const layer = (buf[i + 1]! >> 1) & 3; // 1 = Layer III
    const idx = buf[i + 2]! >> 4;
    if (layer !== 1 || version === 1 || idx === 0 || idx === 15) continue;
    const kbps = (version === 3 ? MP3_BITRATES_V1 : MP3_BITRATES_V2)[idx]!;
    return { bitrateKbps: kbps, offset: i };
  }
  return null;
}

export interface RecordingMeta {
  filename: string;
  device_id: string | null;
  started_at: string;
  duration_seconds: number;
  size_bytes: number;
  modified_at: string;
  /** Still being written by a connected device. */
  active: boolean;
}

export interface StorageStats {
  recordings: number;
  total_bytes: number;
  disk_free_bytes: number | null;
  disk_total_bytes: number | null;
  last_recording: RecordingMeta | null;
}

/**
 * Map a client-supplied filename to a path inside `dir`, or null.
 * Two independent checks: a strict whitelist on the name, then a containment
 * check on the resolved path.
 */
export function resolveRecordingPath(dir: string, filename: string): string | null {
  if (typeof filename !== 'string' || !SAFE_FILENAME.test(filename) || filename.includes('..')) return null;
  const root = path.resolve(dir);
  const full = path.resolve(root, filename);
  if (path.dirname(full) !== root) return null;
  return full;
}

interface CacheEntry {
  size: number;
  mtimeMs: number;
  meta: RecordingMeta;
}

export class RecordingStore {
  private cache = new Map<string, CacheEntry>();
  private active = new Set<string>();

  constructor(
    readonly dir: string,
    private readonly format: PcmFormat,
    private readonly log: Logger,
  ) {}

  async init(): Promise<void> {
    await mkdir(this.dir, { recursive: true });
    await this.removePartials();
    await this.repairAll();
  }

  /** Delete half-written MP3s left by an interrupted conversion (their WAV still exists). */
  private async removePartials(): Promise<void> {
    for (const e of await readdir(this.dir, { withFileTypes: true })) {
      if (e.isFile() && PARTIAL_FILE.test(e.name)) {
        await rm(path.join(this.dir, e.name), { force: true });
        this.log.warn(`Removed interrupted MP3 conversion ${e.name}`);
      }
    }
  }

  /** Finished (not currently recording) WAV files, oldest first — candidates for MP3 conversion. */
  async finishedWavs(): Promise<string[]> {
    return (await this.recordingNames())
      .filter((n) => n.endsWith('.wav') && !this.active.has(n))
      .sort()
      .map((n) => path.join(this.dir, n));
  }

  isActive(filename: string): boolean {
    return this.active.has(filename);
  }

  /** Delete a finished recording. Returns false if it didn't exist. */
  async remove(filename: string): Promise<boolean> {
    const full = resolveRecordingPath(this.dir, filename);
    if (!full) return false;
    try {
      await rm(full);
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === 'ENOENT') return false;
      throw err;
    }
    this.cache.delete(filename);
    return true;
  }

  setActive(filename: string, active: boolean): void {
    if (active) this.active.add(filename);
    else this.active.delete(filename);
  }

  /**
   * Fix recordings whose header was not finalized (server crash / power loss):
   * rewrite the RIFF and data sizes to match what is actually on disk.
   */
  async repairAll(): Promise<number> {
    let repaired = 0;
    for (const name of await this.recordingNames()) {
      if (!name.endsWith('.wav') || this.active.has(name)) continue;
      try {
        if (await this.repair(name)) repaired++;
      } catch (err) {
        this.log.error(`Could not check recording ${name}`, err);
      }
    }
    return repaired;
  }

  private async repair(name: string): Promise<boolean> {
    const full = path.join(this.dir, name);
    const fh = await open(full, 'r+');
    try {
      const { size } = await fh.stat();
      const head = Buffer.alloc(Math.min(size, 4096));
      await fh.read(head, 0, head.length, 0);
      const info = parseWavHeader(head);
      if (!info) {
        if (size <= WAV_HEADER_BYTES) {
          // Crashed between open and first header write; nothing to recover.
          await fh.write(buildWavHeader(this.format, 0), 0, WAV_HEADER_BYTES, 0);
          this.log.warn(`Repaired empty recording ${name}`);
          return true;
        }
        this.log.warn(`Skipping ${name}: not a PCM WAV file`);
        return false;
      }
      const align = Math.max(1, info.channels * (info.bitsPerSample / 8));
      const onDisk = size - info.dataOffset;
      const actual = onDisk - (onDisk % align);
      if (info.dataBytes === actual && info.riffSize === info.dataOffset - 8 + actual) return false;
      if (info.dataOffset !== WAV_HEADER_BYTES) {
        this.log.warn(`Skipping ${name}: header size mismatch but not a file this server wrote`);
        return false;
      }
      await fh.write(buildWavHeader(info, actual), 0, WAV_HEADER_BYTES, 0);
      if (actual !== onDisk) await fh.truncate(info.dataOffset + actual);
      await fh.datasync();
      this.log.warn(`Repaired recording header ${name} (recovered ${(actual / bytesPerSecond(info)).toFixed(1)} s)`);
      return true;
    } finally {
      await fh.close();
    }
  }

  private async recordingNames(): Promise<string[]> {
    const entries = await readdir(this.dir, { withFileTypes: true });
    return entries.filter((e) => e.isFile() && SAFE_FILENAME.test(e.name)).map((e) => e.name);
  }

  /** All recordings, newest first. Header reads are cached by (size, mtime). */
  async list(): Promise<RecordingMeta[]> {
    const names = await this.recordingNames();
    const seen = new Set<string>();
    const out: RecordingMeta[] = [];
    for (const name of names) {
      seen.add(name);
      try {
        out.push(await this.describe(name));
      } catch {
        // File vanished or unreadable between readdir and stat; ignore.
      }
    }
    for (const key of this.cache.keys()) if (!seen.has(key)) this.cache.delete(key);
    return out.sort((a, b) => b.started_at.localeCompare(a.started_at) || b.filename.localeCompare(a.filename));
  }

  private async describe(name: string): Promise<RecordingMeta> {
    const full = path.join(this.dir, name);
    const st = await stat(full);
    const cached = this.cache.get(name);
    const active = this.active.has(name);
    if (cached && cached.size === st.size && cached.mtimeMs === st.mtimeMs) {
      return { ...cached.meta, active };
    }

    let duration = 0;
    const fh = await open(full, 'r');
    try {
      const head = Buffer.alloc(Math.min(st.size, 4096));
      await fh.read(head, 0, head.length, 0);
      if (name.endsWith('.mp3')) {
        // Constant bitrate: duration follows from the size of the audio frames.
        const mp3 = parseMp3Start(head);
        if (mp3) duration = ((st.size - mp3.offset) * 8) / (mp3.bitrateKbps * 1000);
      } else {
        const info = parseWavHeader(head);
        if (info && info.sampleRate > 0) {
          // Trust what's on disk over the header while a file is being written.
          const dataBytes = Math.max(0, Math.min(info.dataBytes, st.size - info.dataOffset));
          duration = dataBytes / bytesPerSecond(info);
        }
      }
    } finally {
      await fh.close();
    }

    const m = NAME_PARTS.exec(name);
    const started = m
      ? new Date(+m[2]!, +m[3]! - 1, +m[4]!, +m[5]!, +m[6]!, +m[7]!)
      : st.birthtimeMs > 0
        ? st.birthtime
        : st.mtime;
    const meta: RecordingMeta = {
      filename: name,
      device_id: m ? m[1]! : null,
      started_at: started.toISOString(),
      duration_seconds: Math.round(duration * 10) / 10,
      size_bytes: st.size,
      modified_at: st.mtime.toISOString(),
      active,
    };
    this.cache.set(name, { size: st.size, mtimeMs: st.mtimeMs, meta });
    return meta;
  }

  async stats(list?: RecordingMeta[]): Promise<StorageStats> {
    const recs = list ?? (await this.list());
    let free: number | null = null;
    let total: number | null = null;
    try {
      const fs = await statfs(this.dir);
      free = fs.bavail * fs.bsize;
      total = fs.blocks * fs.bsize;
    } catch {
      // statfs unsupported on this platform
    }
    return {
      recordings: recs.length,
      total_bytes: recs.reduce((s, r) => s + r.size_bytes, 0),
      disk_free_bytes: free,
      disk_total_bytes: total,
      last_recording: recs[0] ?? null,
    };
  }

  async count(): Promise<number> {
    return (await this.recordingNames()).length;
  }
}
